[33m30a6b76[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m)[m A program to read an employee's data (name,,gross salary, and tax). Then, display the employee's data (name and net salary). Then, increase the employee's salary,by a given percentage (only the,gross salary is affected by the percentage) and display the,employee's data again. Use the class designed below. (programa para ler os dados de um funcionário (nome,,salário bruto e imposto). Em seguida, mostrar os dados do,funcionário (nome e salário líquido). Em seguida, aumentar o salário,do funcionário com base em uma porcentagem dada (somente o,salário bruto é afetado pela porcentagem) e mostrar novamente os,dados do funcionário. Use a classe projetada abaixo.)
[33mae79438[m program to read the width and height values ​​of a rectangle. Then display the area, perimeter, and diagonal values ​​on the screen using a class (programa para ler os valores da largura e altura de um retângulo. Em seguida, mostrar na tela o valor de sua área, perímetro e diagonal, usando uma classe)
[33m97ec724[m classes, objects and attributes2 (classes, objetos e atributos2)
[33m109c40b[m classes, objects and attributes (classes, objetos e atributos)
[33mcc7acd2[m creating a class with three attributes to better present a triangle (criando uma clase com três atributos para representar melhor um triângulo)
[33m0aae314[m class creation2 (criação de classe2)
[33m723c768[m class creation (criação de classe)
[33m9d6ae40[m solving problems without object orientation (resolvendo problema sem orientação a objetos)
[33m18e6ed6[m result of Y (resultado de Y)
[33mdd7daf1[m Make a program to read the measures of the sides of two triangles X and Y (Fazer um programa para ler as medidas dos lados de dois triângulos X e Y)
[33m6a43292[m solving a problem without object orientation (resolvendo um problema sem orientação a objetos)
[33med9ba73[m functions (funcoes)
[33md5d4676[m functions (funcoes)
[33m9db465f[m new project2 (novo projeto2)
[33m6b8daf2[m new project (novo projeto)
[33m4f8ebeb[m arithmetic operators (operadores aritméticos)
[33mc68b511[m testing minimum and maximum value of int (testando valor minímo e máximo de int)
[33m8aab3d5[m testing minimum value of int (testando valor minímo de int)
[33m3ba6feb[m Testing new types of variables and objects (Teste de novos tipos de variáveis e objetos)
[33m25ec17f[m Testing new types of variables (Teste de novos tipos de variáveis)
[33m250b006[m New line options for braces (Novas opções de linhas para chaves)
[33m3b36f79[m Rename namespace (Renomear namespace)
[33mf6dfa34[m The new output uses recent C# features - (A nova saída usa recursos recentes do C#)
[33mb12a0db[m test
[33mfb0c6ac[m second commit
[33m0abb27a[m first commit
